### PR TITLE
update themes + migrate discord embeds to github

### PR DESCRIPTION
**Pull request by ItMePeachy**

### CODE REVIEW

**Comment by ItMePeachy** [comment]
fixed codefactor

**Review by papertek — CHANGES_REQUESTED** [review]
update the rest of the themes

**Comment by ItMePeachy** [comment]
FREAKUGN UPDAETD THEMES TOO DO THE PULL REQUEST AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Review by papertek — APPROVED** [review]
seems ok

**Pull request merged**
